### ISSUE TITLE
Cant run in VS2015 from .sln file

### ISSUE THREAD

**Issue by rogersbrad** [scottbrady91/IdentityManager2-Example#1]
clicked to download zip file.  did at least 2 times. open project/solution using the outer.sln file, gets an error:

IdentityManager2-Example-master\src\IdentityServer\IdentityServer.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\aaa\Downloads\IdentityManager2-Example-master (1)\IdentityManager2-Example-master\src\IdentityServer\IdentityServer.csproj

**Comment by scottbrady91** [comment]
Hi! IdentityManager2 is for ASP.NET Core, which if I recall correctly can only be opened in VS2017.
