### ISSUE TITLE
404 when attempting to use version 1.0.0

### ISSUE THREAD

**Issue by smokeport** [scottbrady91/IdentityManager2-Example#2]
When I updated the IdentityManager2 package to 1.0.0 I also had to start using .Net Core 3.1.

After doing this I get a 404 when attempting to start IdentityManager2-Example (previously it was working).

Is there some sort of routing or mapping that needs to be added to Startup.Configure ?

**Comment by scottbrady91** [comment]
Hi! Sorry about the delay.

I've updated the sample to .NET Core 3.1 but it sounds like you may have been missing some of the new ASP.NET Core routing middleware.
